### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [slowstab/gal#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by fawni** [comment]
this was originally just my personal theme hosted on git services, which is why there was no readme.
i added a preview now, markdown infuriates me so i hope this is good enough.

ps: thank you for [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), it's how i found zinit (<3) and a lot of cool plugins!
